package com.parcao.model.enums;

public enum MensagemEnum {
    INEXISTENTE("INEXISTENTE"),
    USUARIO_JA_EXISTE("USUARIO JÁ EXISTE"),
    USUARIO_NAO_EXISTE("USUARIO NÃO EXISTE"),
    SUCESSO("SUCESSO"),
    PASSWORD_INCORRETO("PASSWORD INCORRETO"),
    PEDIDO_REALIZADO_COM_SUCESSI("PEDIDO REALIZADO COM SUCESSO"),
    PRODUTO_ESTOQUE_GERAL_INSUFICIENTE("PRODUTO ESTOQUE GERAL INSUFICIENTE"),
    PRODUTO_NAO_ENCONTRADO("PRODUTO NÃO ENCONTRADO"),
    PRODUTO_ATUALIZADO_COM_SUCESSO("PRODUTO ATUALIZADO COM SUCESSO"),
    PRODUTO_EXCLUIDO_COM_SUCESSO("PRODUTO EXCLUIDO COM SUCESSO"),
    PRODUTO_JA_CADASTRADO("PRODUTO JÁ CADASTRADO"),
    ROLE_INEXISTENTE("ROLE INEXISTENTE"),
    FILIAL_INEXISTENTE("FILIAL_INEXISTENTE"),
    SENHA_ALTERADA_COM_SUCESSO("SENHA ALTERADA COM SUCESSO"),
    SENHA_INCORRETA("SENHA INCORRETA"),
    SENHAS_VAZIAS("AS SENHAS NÃO PODEM SER VAZIAS"),;


    private final String mensagem;

    MensagemEnum(String mensagem) {
        this.mensagem = mensagem;
    }

    public String getMensagem() {
        return mensagem;
    }
}
