package com.parcao.enums;

public enum MensagemEnum {
    INEXISTENTE("INEXISTENTE"),
    USUARIO_JA_EXISTE("USUARIO JÁ EXISTE"),
    USUARIO_NAO_EXISTE("USUARIO NÃO EXISTE"),
    SUCESSO("SUCESSO"),
    PASSWORD_INCORRETO("PASSWORD INCORRETO"),
    PEDIDO_REALIZADO_COM_SUCESSI("PEDIDO REALIZADO COM SUCESSO"),
    PRODUTO_ESTOQUE_GERAL_INSUFICIENTE("PRODUTO_ESTOQUE_GERAL_INSUFICIENTE"),
    PRODUTO_NAO_ENCONTRADO("PRODUTO NÃO ENCONTRADO"),
    PRODUTO_ATUALIZADO_COM_SUCESSO("PRODUTO ATUALIZADO COM SUCESSO"),
    PRODUTO_EXCLUIDO_COM_SUCESSO("PRODUTO EXCLUIDO COM SUCESSO"),
    PRODUTO_JA_CADASTRADO("PRODUTO JÁ CADASTRADO"),
    ROLE_INEXISTENTE("ROLE INEXISTENTE"),
    FILIAL_INEXISTENTE("FILIAL_INEXISTENTE"),
    SENHA_ALTERADA_COM_SUCESSO("SENHA ALTERADA COM SUCESSO"),
    SENHA_INCORRETA("SENHA INCORRETA"),
    SENHAS_VAZIAS("AS SENHAS NÃO PODEM SER VAZIAS"),
    ESTOQUE_PRODUTO_FILIAL_ATUALIZADO("ESTOQUE_PRODUTO_FILIAL_ATUALIZADO"),
    ESTOQUE_FILIAL_ATUALIZADO("ESTOQUE_FILIAL_ATUALIZADO"),
    ERRO_AO_ATUALIZAR_ESTOQUE("ERRO_AO_ATUALIZAR_ESTOQUE"),
    FILIAL_JA_CADASTRADA("FILIAL_JA_CADASTRADA"),
    FILIAL_NAO_EXISTE("FILIAL_NAO_EXISTE"),
    TAXA_JA_CADASTRADA("TAXA_JA_CADASTRADA"),
    TAXA_NAO_ENCONTRADA("TAXA_NAO_ENCONTRADA"),
    CLIENTE_NAO_ENCONTRADO("CLIENTE_NAO_ENCONTRADO"),
    CLIENTE_NAO_EXISTE("CLIENTE_NAO_EXISTE"),
    TELEFONE_JA_CADASTRADO("TELEFONE_JA_CADASTRADO"),
    SALDO_INSUFICIENTE("SALDO_INSUFICIENTE"),
    EXCLUIDO_COM_SUCESSO("EXCLUIDO_COM_SUCESSO"),
    SALDO_CLIENTE_ATUALIZADO("SALDO_CLIENTE_ATUALIZADO"),
    FECHAMENTO_CAIXA_NAO_ENCONTRADO("FECHAMENTO_CAIXA_NAO_ENCONTRADO"),
    SEM_DADOS_ESTATISTICOS("SEM_DADOS_ESTATISTICOS"),
    TIPO_DE_PAGAMENTO_NAO_ENCONTRADO("TIPO_DE_PAGAMENTO_NA0_ENCONTRADO");


    private final String mensagem;

    MensagemEnum(String mensagem) {
        this.mensagem = mensagem;
    }

    public String getMensagem() {
        return mensagem;
    }
}
